### PR TITLE
Jmh

### PR DESCRIPTION
**Pull request by twillouer**
Hi,

I work with "Jaro" on a project, and the Profiler spot some things who can be optimized.

from:
   JaroBench.compare  Web Database Applications  WebRAD: Building Database Applications on the Web with Visual FoxPro and Web Connection  thrpt  200  814285,208 ± 10236,226  ops/s
   JaroBench.compare  Web Database Applications  WebRAD: Building Database Applications on the Web with Visual FoxPro and Web Connection   avgt   15    1207,234 ±    65,726  ns/op

to: (after the optimisation)
  JaroBench.compare  Web Database Applications  WebRAD: Building Database Applications on the Web with Visual FoxPro and Web Connection  thrpt  200  1303910,930 ± 8807,522  ops/s
 JaroBench.compare  Web Database Applications  WebRAD: Building Database Applications on the Web with Visual FoxPro and Web Connection   avgt   15      763,480 ±   29,435  ns/op

If you don't want the bench structure and only the optimization, you can take the latest commit.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Very interesting. Checking it out.

**Comment by twillouer** [comment]
sorry for travis, corrected..

**Comment by mpkorstanje** [comment]
I've implemented your optimizations [and added few more](https://github.com/Simmetrics/simmetrics/commit/0db383164a5672307d641126c5e660abcde8f2ff). These have been released as version 3.0.2 and should be available on maven central in about 2 hours. Search results may take longer to update.

Used caliper for benchmarking. [Shows very nice results indeed!](https://microbenchmarks.appspot.com/runs/3f4b0689-3f17-4c53-821c-a940bc75f831#r:scenario.benchmarkSpec.parameters.method). Thanks allot.

There is probably a bit more that can be done to optimize. getCommonCharacters only destroys charsB, so charsA could be reused. Another optimization would be  skipping making a copy of common, it won't matter for the score because both (a,b) and (b,a) have the same length and are zero padded. But I don't have time to expand the Caliper test today.

**Comment by mpkorstanje** [comment]
FYI: 3.0.3 is going up. Added the optimizations mentioned above for Jaro. Just about the most that can be done without mangling the code into unreadability.

[Caliper](https://microbenchmarks.appspot.com/runs/da3bc391-9ec3-42a1-a740-c82d3e29a92d#r:scenario.benchmarkSpec.parameters.method).

**Pull request closed without merging**
